# Generated by Django 4.2.5 on 2023-10-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dealer_alter_contact_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dealer',
        ),
    ]
