# Generated by Django 4.2.5 on 2023-10-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('email', models.TextField(blank=True)),
                ('ph_number', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
