# Generated by Django 4.2.5 on 2023-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='subject',
            field=models.TextField(max_length=100),
        ),
    ]
