# Generated by Django 4.2.5 on 2023-10-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0003_alter_dealer_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='subject',
            new_name='message',
        ),
    ]
