# Generated by Django 4.2.5 on 2023-11-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0004_rename_subject_dealer_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('email', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
